DATA_PATH: 'data/'
LLM: 'phi'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
WEAVIATE_URL: 'http://localhost:8080'
INDEX_NAME: 'Sparrow'
CHUNK_SIZE: 1000
# OLLAMA_BASE_URL: 'http://192.168.68.110:11434'